### ISSUE TITLE
App not working in discord

### ISSUE THREAD

**Issue by lifelikesubset** [msciotti/magic-search#3]
When I first installed the app it worked perfectly, but now we are unable to search any card successfully. Now it says loading options failed when trying to search, and then shows up with a message that says this interaction failed after searching.

**Comment by epochcoding** [comment]
I've been having the same issue. 
![Screenshot 2024-08-15 103259](https://github.com/user-attachments/assets/69ba9de6-654e-4e85-9b06-dbab55e9a015)

**Comment by msciotti** [comment]
So sorry this has been broken for so long. I did not have proper logging to understand when it was broken. There was an underlying API change in Scryfall that has been fixed, and it's working again as of a month ago or so
